// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkON4Fz8yc23SADhvxcARtW6_OTJwfns',
    appId: '1:769027848160:web:f3a99736655a2e8aa4dd85',
    messagingSenderId: '769027848160',
    projectId: 'graduation-project-c880c',
    authDomain: 'graduation-project-c880c.firebaseapp.com',
    storageBucket: 'graduation-project-c880c.firebasestorage.app',
    measurementId: 'G-YK6N625SB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpm4iQ-NiC9-TD4UBPgGZFTvOn8rw5cI',
    appId: '1:769027848160:android:0fdd8953c8973434a4dd85',
    messagingSenderId: '769027848160',
    projectId: 'graduation-project-c880c',
    storageBucket: 'graduation-project-c880c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLNiqORE5WWNK4ghugnMj5TCXUTKYufY',
    appId: '1:769027848160:ios:fef54f91faa331cea4dd85',
    messagingSenderId: '769027848160',
    projectId: 'graduation-project-c880c',
    storageBucket: 'graduation-project-c880c.firebasestorage.app',
    iosBundleId: 'com.agrivision.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLNiqORE5WWNK4ghugnMj5TCXUTKYufY',
    appId: '1:769027848160:ios:fef54f91faa331cea4dd85',
    messagingSenderId: '769027848160',
    projectId: 'graduation-project-c880c',
    storageBucket: 'graduation-project-c880c.firebasestorage.app',
    iosBundleId: 'com.agrivision.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVkON4Fz8yc23SADhvxcARtW6_OTJwfns',
    appId: '1:769027848160:web:678492c7e8b3b8e1a4dd85',
    messagingSenderId: '769027848160',
    projectId: 'graduation-project-c880c',
    authDomain: 'graduation-project-c880c.firebaseapp.com',
    storageBucket: 'graduation-project-c880c.firebasestorage.app',
    measurementId: 'G-BVBPGECP53',
  );
}
